apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: reviews-lua
  namespace: default
spec:
  workloadSelector:
    labels:
      app: reviews
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 9080
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
          inlineCode: |
            function envoy_on_request(request_handle)
              request_handle:logInfo("Authority: "..request_handle:headers():get(":authority"))
              request_handle:logInfo("Method: "..request_handle:headers():get(":method"))
              request_handle:logInfo("Path: "..request_handle:headers():get(":path"))
              -- Make an HTTP call to an upstream host with the following headers, body, and timeout.
              local headers, body = request_handle:httpCall(
                "lua_cluster",
                {
                  [":method"] = "POST",
                  [":path"] = "/acl",
                  [":authority"] = "727439ccbe264ad3965f4b824dbdbee1.m.pipedream.net"
                },
                "authorize call",
                5000)
                request_handle:logCritical("Auth Response:" .. headers[":status"])
                request_handle:logCritical("Auth Body:" .. body)
            end
            function envoy_on_response(response_handle)
              -- Log response status code
              response_handle:logInfo("Status: "..response_handle:headers():get(":status"))
            end
  # The second patch adds the cluster that is referenced by the lua code
  # cds match is omitted as a new cluster is being added
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value: # cluster specification
        name: "lua_cluster"
        type: STRICT_DNS
        connect_timeout: 0.5s
        lb_policy: ROUND_ROBIN
        transport_socket:
            name: tls
        hosts:
        - socket_address:
            protocol: TCP
            address: "727439ccbe264ad3965f4b824dbdbee1.m.pipedream.net"
            port_value: 443