apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-reqauth"
spec:
  selector:
    matchLabels:
      app: reviews
  jwtRules:
  - issuer: "https://login.axway.com/auth/realms/Broker"
    jwksUri: "https://login.axway.com/auth/realms/Broker/protocol/openid-connect/certs"
    outputPayloadToHeader: authtok
    forwardOriginalToken: true
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "jwt-authpol"
spec:
  selector:
    matchLabels:
      app: reviews
  action: ALLOW
  rules:
    - when:
        - key: request.auth.claims[iss]
          values: ["https://login.axway.com/auth/realms/Broker"]