apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-reqauth
spec:
  selector:
    matchLabels:
      app: reviews
  jwtRules:
  - issuer: "https://login.axway.com/auth/realms/Broker"
    jwksUri: "https://login.axway.com/auth/realms/Broker/protocol/openid-connect/certs"
