apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-reqauth
spec:
  selector:
    matchLabels:
      app: reviews
  jwtRules:
  - issuer: "https://sso-authentication-hub.apps.azuwepoc012l.6dba7406dcaf4075b252.westeurope.aksapp.io/auth/realms/poc"
    jwksUri: "https://sso-authentication-hub.apps.azuwepoc012l.6dba7406dcaf4075b252.westeurope.aksapp.io/auth/realms/poc/protocol/openid-connect/certs"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "jwt-authpol"
spec:
  selector:
    matchLabels:
      app: reviews
  action: ALLOW
  rules:
    - when:
        - key: request.auth.claims[iss]
          values: ["https://sso-authentication-hub.apps.azuwepoc012l.6dba7406dcaf4075b252.westeurope.aksapp.io/auth/realms/poc"]